sudo: required

services:
  - docker

before_install:
  - docker build -t federicogarcia/react-client -f ./client/Dockerfile.dev ./client

script:
  - docker run federicogarcia/react-client npm test -- --coverage

after_sucess:
  - docker build -t federicogarcia/fibo-app-client ./client
  - docker build -t federicogarcia/fibo-app-nginx ./nginx
  - docker build -t federicogarcia/fibo-app-server ./server
  - docker build -t federicogarcia/fibo-app-worker ./worker
  # Now upload production images to the Docker Registry
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push federicogarcia/fibo-app-client
  - docker push federicogarcia/fibo-app-nginx
  - docker push federicogarcia/fibo-app-server
  - docker push federicogarcia/fibo-app-worker
