sudo: required

services:
  - docker

before_install:
  - docker build -t federicogarcia/react-client -f ./client/Dockerfile.dev ./client

script:
  - docker run federicogarcia/react-client npm test -- --coverage

after_success:
  - docker build -t federicogarcia/fibo-app-client ./client
  - docker build -t federicogarcia/fibo-app-nginx ./nginx
  - docker build -t federicogarcia/fibo-app-server ./server
  - docker build -t federicogarcia/fibo-app-worker ./worker
  # Now upload production images to the Docker Registry
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push federicogarcia/fibo-app-client
  - docker push federicogarcia/fibo-app-nginx
  - docker push federicogarcia/fibo-app-server
  - docker push federicogarcia/fibo-app-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "fibo-app"
  env: "FiboApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-510033969879"
  bucket_path: "fibo-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"